[colors]
ansi = [
    "#1a1a1a",
    "#b34747",
    "#47b347",
    "#ccad52",
    "#3d85cc",
    "#b347b3",
    "#36b3b3",
    "#cccac2",
]
background = "#1b1b26"
brights = [
    "#4d4d4d",
    "#e65c5c",
    "#5ce65c",
    "#ffdc69",
    "#4da6ff",
    "#e673e6",
    "#45e6e6",
    "#fffdf2"
]
cursor_bg = "#ff007b"
cursor_border = "#ff007b"
foreground = "#e6e6cf"

[metadata]
name = "pax"
