[colors]
ansi = [
    "#1b1b26",
    "#b34747",
    "#47b347",
    "#ccad52",
    "#3d85cc",
    "#b347b3",
    "#36b3b3",
    "#ccccad",
]
background = "#1b1b26"
brights = [
    "#36364d",
    "#e65c5c",
    "#5ce65c",
    "#ffd966",
    "#4da6ff",
    "#e65ce6",
    "#45e6e6",
    "#ffffd9"
]
cursor_bg = "#ff007b"
cursor_border = "#ff007b"
foreground = "#e6e6cf"

[metadata]
name = "pax"
