[colors]
ansi = [
    "#1a1a1a",
    "#b35959",
    "#59b359",
    "#ccb866",
    "#7aa3cc",
    "#b359b3",
    "#59b3b3",
    "#cccac2",
]
background = "#1e1e2e"
brights = [
    "#4d4d4d",
    "#e66e6e",
    "#6ee66e",
    "#ffdc69",
    "#99ccff",
    "#e673e6",
    "#6ee6e6",
    "#fffdf2",
]
cursor_bg: "#ff007b"
cursor_border: "#ff007b"
foreground: "#e9e7dd"
