#!/usr/bin/env bash

# NAMING:
# linear id:    RVR-12345
# branch:       art/rvr-12345-free-description
# worktree dir: ~/code/altowt/art/rvr-12345-free-description  (chosen by `alto worktree new`)
# tmux session: rvr-12345

selected=$(
  curl -s -X POST https://api.linear.app/graphql \
    -H "Authorization: $LINEAR_API_KEY" \
    -H "Content-Type: application/json" \
    -d '{ "query": "{ viewer { assignedIssues(filter: { state: { type: { nin: [\"started\", \"completed\", \"canceled\"] } } }) { nodes { identifier title } } } }"}' \
  | jq -r '.data.viewer.assignedIssues.nodes[] | "\(.identifier)\t\(.title)"' \
  | fzf --delimiter='\t'
)

[[ -z "$selected" ]] && exit 1

id=$(echo "$selected" | cut -f1)

read -p "Short description: " description
[[ -z "$description" ]] && exit 1

id_slug=$(echo "$id" | tr '[:upper:]' '[:lower:]' | tr ' ' '-')
desc_slug=$(echo "$description" | tr '[:upper:]' '[:lower:]' | tr ' ' '-')
branch="art/${id_slug}-${desc_slug}"

if ! tmux has-session -t "$id_slug" 2>/dev/null; then
  wt_path=$(cd ~/code/alto && ./bin/alto worktree new "$branch" --print-path)
  cd "$wt_path" || exit 1
fi

art-session.sh ~/code/layouts/alto.tmux "$id_slug"
